# Generated by Django 6.0.7 on 2026-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_total_value_alter_orderitem_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='', help_text='Cidade', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_complement',
            field=models.CharField(blank=True, help_text='Complemento', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_neighborhood',
            field=models.CharField(default='', help_text='Bairro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_number',
            field=models.CharField(default=' ', help_text='Número', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(default=' ', help_text='UF', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_street',
            field=models.CharField(default='cep', help_text='Rua de entrega', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zip_code',
            field=models.CharField(default='cep1', help_text='CEP de entrega', max_length=8),
            preserve_default=False,
        ),
    ]
