# Generated by GitHub Copilot on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancellation_reason_order_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora da confirmação de pagamento', null=True),
        ),
    ]
