# Generated by Django 6.0.7 on 2026-07-10 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', help_text='Status de aprovação do cliente', max_length=10)),
                ('customer_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2)),
                ('nickname', models.CharField(help_text='Apelido ou Nome Fantasia', max_length=100)),
                ('company_name', models.CharField(blank=True, help_text='Razão Social (Opcional)', max_length=150, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter 11 dígitos')])),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve conter 14 dígitos')])),
                ('cnpj_cpf', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\d{11,14}$', 'Documento deve conter apenas números (11 a 14 dígitos)')])),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Telefone deve ter 10 ou 11 dígitos puros')])),
                ('zip_code', models.CharField(help_text='CEP apenas números', max_length=8)),
                ('street', models.CharField(help_text='Rua, Avenida, etc.', max_length=150)),
                ('number', models.CharField(help_text='Número ou S/N', max_length=20)),
                ('complement', models.CharField(blank=True, help_text='Apartamento, Bloco, etc.', max_length=100, null=True)),
                ('neighborhood', models.CharField(help_text='Bairro', max_length=100)),
                ('city', models.CharField(help_text='Cidade', max_length=100)),
                ('state', models.CharField(help_text='UF (ex: SP)', max_length=2)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Data/hora da aprovação', null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin que aprovou o cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_customers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nickname'],
                'indexes': [models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx'), models.Index(fields=['nickname'], name='customers_c_nicknam_3b81ae_idx'), models.Index(fields=['status'], name='customers_c_status_ce44cf_idx'), models.Index(fields=['cpf'], name='customers_c_cpf_93e83b_idx'), models.Index(fields=['cnpj'], name='customers_c_cnpj_ab7373_idx')],
            },
        ),
    ]
