# Generated by Django 6.0.7 on 2026-07-10 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora do bloqueio', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='Admin que bloqueou o cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Cliente Aprovado'), ('BLOCKED', 'Cliente Bloqueado'), ('PASSWORD_SET', 'Senha Definida/Alterada'), ('CREDIT_LIMIT_UPDATED', 'Limite de Crédito Atualizado'), ('UNBLOCKED', 'Cliente Desbloqueado')], help_text='Tipo de ação realizada', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data e hora da ação')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detalhes adicionais (ex: credit_limit anterior/novo)')),
                ('admin_user', models.ForeignKey(help_text='Admin que realizou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Cliente afetado pela ação', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='customers.customer')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['customer', '-timestamp'], name='customers_c_custome_cc0939_idx'), models.Index(fields=['action', '-timestamp'], name='customers_c_action_379d91_idx'), models.Index(fields=['admin_user', '-timestamp'], name='customers_c_admin_u_64d15b_idx')],
            },
        ),
    ]
