# Generated by Django 6.0.7 on 2026-07-08 12:28

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['nickname']},
        ),
        migrations.AddField(
            model_name='customer',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\d{11,14}$', 'Documento deve conter apenas números (11 a 14 dígitos)')]),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Razão Social (Opcional)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_address',
            field=models.TextField(default='Sem endereco', help_text='Endereço padrão de entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='nickname',
            field=models.CharField(default='Sem Apelido', help_text='Apelido ou Nome Fantasia', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Telefone deve ter 10 ou 11 dígitos puros')]),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['nickname'], name='customers_c_nicknam_3b81ae_idx'),
        ),
    ]
