# Generated by Django 6.0.7 on 2026-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_customer_cnpj_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Sem nome', help_text='Cidade', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='complement',
            field=models.CharField(blank=True, help_text='Apartamento, Bloco, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='neighborhood',
            field=models.CharField(default='Sem endereco', help_text='Bairro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(default='', help_text='Número ou S/N', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='', help_text='UF (ex: SP)', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='', help_text='Rua, Avenida, etc.', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default='', help_text='CEP apenas números', max_length=8),
            preserve_default=False,
        ),
    ]
