# Generated by Django 6.0.7 on 2026-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_blocked_at_customer_blocked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='access_password_ciphertext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
