# Generated by Django 6.0.7 on 2026-07-08 20:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_delivery_address_customer_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora da aprovação', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin que aprovou o cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve conter 14 dígitos')]),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter 11 dígitos')]),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', help_text='Status de aprovação do cliente', max_length=10),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='customers_c_status_ce44cf_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['cpf'], name='customers_c_cpf_93e83b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['cnpj'], name='customers_c_cnpj_ab7373_idx'),
        ),
    ]
